# ./frontend/Dockerfile

# Use a lightweight Node.js image
FROM node:14-alpine

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Start the development server on port 5173
EXPOSE 5173
CMD ["npm", "run", "dev"]
