# ./frontend/Dockerfile

# Use a lightweight Node.js image
FROM node:14-alpine

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Build the React application
RUN npm run build

# Serve the application on port 3000
EXPOSE 3000
CMD ["npm","run","dev"]
