version: '3'
services:
  backend:
    build:
      context: ./server  # Path to the backend directory
      dockerfile: Dockerfile  # Optional if the file is named Dockerfile
    image: omegle-clone-backend
    ports:
      - "8000:8000"  # Backend exposed on port 8000
    networks:
      - app-network

  frontend:
    build:
      context: ./client  # Path to the frontend directory
      dockerfile: Dockerfile  # Optional if the file is named Dockerfile
    image: omegle-clone-frontend
    ports:
      - "5173:5173"  # Frontend exposed on port 5173
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
