version: '3'
services:
  backend:
    build:
      context: ./server  # Path to the backend directory
      dockerfile: Dockerfile
    image: omegle-clone-backend
    ports:
      - "8000:8000"  # Exposing the backend API on port 8000 on the host and container
    networks:
      - app-network

  frontend:
    build:
      context: ./client  # Path to the frontend directory
      dockerfile: Dockerfile
    image: omegle-clone-frontend
    ports:
      - "5173:5173"  # Exposing the frontend on port 5173 on the host and container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
