version: '3'
services:
  backend:
    image: omegle-clone-backend
    build:
      context: ./server
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    image: omegle-clone-frontend
    build:
      context: ./client
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
